export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const LOGOUT_START = 'LOGOUT_START';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';

export const GET_USER_START = 'GET_USER_START';
export const GET_USER_SUCCCESS = 'GET_USER_SUCCCESS';
export const GET_USER_ERROR = 'GET_USER_ERROR';

export const FETCH_ANIMALS_START = 'FETCH_ANIMALS_START';
export const FETCH_ANIMALS_SUCCESS = 'FETCH_ANIMALS_SUCCESS';
export const FETCH_ANIMALS_ERROR = 'FETCH_ANIMALS_ERROR';
